steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'buildgcp']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "express/app.yaml"]
